[package]
name = "toccata"
description = "Desktop CD Audio ripper"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
tauri = { version = "2.11.5", features = [] }
toccata-core = { path = "../crates/core" }
